### ISSUE TITLE
Is there a free Comment Mail Pro trial?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#32]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Is there a free Comment Mail Pro trial?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/32
```
---

Yes, you may download Comment Mail Lite from WordPress.org - [Comment Mail Lite](https://wordpress.org/plugins/comment-mail/) and preview Comment Mail Pro's features.

If you are undecided on if you want to upgrade to Pro or not, it is possible to 'Preview Pro Features' via Comment Mail Lite by clicking the corresponding header link. Comment Mail Pro has numerous useful features not available in Comment Mail Lite that will enhance your Subscriptions and over-all user experience.

![preview pro](https://user-images.githubusercontent.com/13220018/27224624-c499ff02-52c8-11e7-9886-9d098690d419.png)

![preview pro features](https://user-images.githubusercontent.com/13220018/27224687-1920bd40-52c9-11e7-9b2a-5972ec12150a.png)

![pro upgrade](https://user-images.githubusercontent.com/13220018/27224708-354c623a-52c9-11e7-9ff3-142f4be0c97b.png)

If you wish to upgrade to Comment Mail Pro, you can do this via [Comment-Mail.com](https://comment-mail.com/) and purchase a Single-Site or Unlimited-Site License.

Clicking the 'Pro Upgrade' link in the Comment Mail Lite version will also redirect you to the website.

**Comment by renzms** [comment]
@raamdev Please check thanks!

**Comment by raamdev** [comment]
I suggest reframing the title of this question to, "Is there a free Pro trial?" and then adjusting the opening part of the KB Article to reflect answering that question.

Also, please add an arrow pointing to the "Preview Pro Features" link in that screenshot.

**Comment by renzms** [comment]
@raamdev 

- Change Title
- Changed some of the wording
- Added in headings and repositioned images
- Added and edited new screenshots

Please check thanks!

**Comment by raamdev** [comment]
Feedback:

- When changing the title, don't forget to change the YAML markup (`title:`). The YAML markup is what defines the title that gets generated in WordPress when the KB Article is imported over there, so it's important that's updated too.
- I'd remove the "Preview Pro Features" bold text, as the screenshot is enough.
- Red arrows instead of blue, as blue doesn't stand out enough.
- I'd add one or two smallish red arrows to the Pro Preview screenshot, pointing out the "Pro Version Only" labels to help pull attention to the fact that all those greyed out panels are Pro-only features.
- "You can also become a Beta Tester and be sent a free copy of the latest version of Comment Mail Lite. As a Beta Tester, you will be able to try out a Release Candidate version, which may contain a preview of features for a Beta version of Comment Mail Pro." ← I'd remove that entire paragraph; it feels out of place in this question about a Pro trial. Only Pro customers receive Pro beta's.
- "`Pro Upgrade` link" — Please don't use code style when referring to button labels or menus; this should be "'Pro Upgrade' link".
- "Comment Mail website" — This should be "[Comment-Mail.com](https://Comment-Mail.com)", (and remove 'website').  
- "a Single Site or Unlimited License." — This should be "a Single-Site or Unlimited-Site license".

**Comment by renzms** [comment]
@raamdev 

Changed:

- [x] When changing the title, don't forget to change the YAML markup (title:). The YAML markup is what defines the title that gets generated in WordPress when the KB Article is imported over there, so it's important that's updated too.
- [x] I'd remove the "Preview Pro Features" bold text, as the screenshot is enough.
- [x] Red arrows instead of blue, as blue doesn't stand out enough.
- [x] I'd add one or two smallish red arrows to the Pro Preview screenshot, pointing out the "Pro Version Only" labels to help pull attention to the fact that all those greyed out panels are Pro-only features.
- [x] "You can also become a Beta Tester and be sent a free copy of the latest version of Comment Mail Lite. As a Beta Tester, you will be able to try out a Release Candidate version, which may contain a preview of features for a Beta version of Comment Mail Pro." ← I'd remove that entire paragraph; it feels out of place in this question about a Pro trial. Only Pro customers receive Pro beta's.
- [x] "Pro Upgrade link" — Please don't use code style when referring to button labels or menus; this should be "'Pro Upgrade' link".
- [x] "Comment Mail website" — This should be "Comment-Mail.com", (and remove 'website').
- [x] "a Single Site or Unlimited License." — This should be "a Single-Site or Unlimited-Site license".
- [x]  Updated Screenshots

Ready for check, thanks!

**Comment by raamdev** [comment]
Looks great! I see you missed one: 

> "Pro Upgrade link" — Please don't use code style when referring to button labels or menus; this should be "'Pro Upgrade' link".

The "Preview Pro Features" link is still useing code style.

**Comment by renzms** [comment]
@raamdev Updated! :)

**Comment by raamdev** [comment]
@renzms Please see my edits here: https://github.com/websharks/comment-mail-kb/commit/f43ad40dd193e7d30587fbe954cdc122124c9cab
