### ISSUE TITLE
Can members modify their existing subscriptions?

### ISSUE THREAD

**Issue by renzms** [websharks/comment-mail-kb#40]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)
##### Additional TODOs

_Additional TODO list items go here._

```yaml
toc-enable: off
title: Can members modify their existing subscriptions?
categories: questions
tags: pre-sale-faqs
author: renzms
github-issue: https://github.com/websharks/comment-mail-kb/issues/40
```
---

Yes, subscribers can modify and manage their existing subscription by accessing their **My Comment Subscription** Page via the link found at the bottom of the page whenever subscribing to a comment. Subscribers can also find this link in the footer of any notification emails they receive.

![confirmation](https://user-images.githubusercontent.com/13220018/27346553-317d1816-5620-11e7-8cf9-0d0eadccaf84.png)

From the My Comment Subscriptions page, they can then customize their subscriptions from a number of different options such as: the email used for receiving updates for the Subscription, displayed Name, the specific Post they wish to subscribe to, specific Comments / Comment Threads / Replies or even All Comments / Replies, and even how often they receive notifications for updates.

![choose post](https://user-images.githubusercontent.com/13220018/27346736-a98cec8c-5620-11e7-9e8c-43f32702c8ec.png)

![edit](https://user-images.githubusercontent.com/13220018/27346856-1d290db0-5621-11e7-8fd7-5d15b958895d.png)

![subscription](https://user-images.githubusercontent.com/13220018/27346995-89e8dc5a-5621-11e7-86c5-52cfce5bcc6e.png)

![changing subscription](https://user-images.githubusercontent.com/13220018/27347103-e18c748a-5621-11e7-9a0a-a7420eff778a.png)

**Comment by renzms** [comment]
@raamdev Please check thanks!

**Comment by raamdev** [comment]
Looks good! The screenshots only show examples of "Add New Subscription" but the question asks about _modifying_ a subscription. Could you also include a screenshot that shows a subscription being modified?

**Comment by renzms** [comment]
@raamdev 

- Updated Screenshots
- Added New titles for images
- Some added details

Please check thanks!

**Comment by raamdev** [comment]
@renzms Looks a lot better! A bit of feedback:

- Please use red arrows and red boxes—blue arrows and boxes blend in way too much and it's hard to tell if they're part of the screenshot or something you added. The box border thickness could be about half as thick as they are.
- Are you using Snagit for screenshots? Adding a border and a bit of dropshadow makes screenshots so much nicer and makes it so that they don't feel like they bleed into the page (e.g., a white background in the screenshot against a white background of the page makes it hard to see where the screenshot actually ends). With Snagit, this can be accomplished with literally 2 clicks:

![2017-05-25_18-42-09](https://cloud.githubusercontent.com/assets/53005/26473684/e7bd1168-417a-11e7-8437-376786d96de5.png)
- You mention that subscribers can access the **My Subscriptions** page after subscribing—where else can they access it from? (The footer of any emails they receive.) I recommend mentioning that as well (a screenshot of that is not necessary).
- "Comments/" needs a space after 'Comments'
- "Choosing Post", "Choosing Comment"—these should be headers and not just bold text. I suggest H3.

**Comment by renzms** [comment]
@raamdev 

Changed:

- [x] Please use red arrows and red boxes—blue arrows and boxes blend in way too much and it's hard to tell if they're part of the screenshot or something you added. The box border thickness could be about half as thick as they are.
- [x] Are you using Snagit for screenshots? Adding a border and a bit of dropshadow makes screenshots so much nicer and makes it so that they don't feel like they bleed into the page (e.g., a white background in the screenshot against a white background of the page makes it hard to see where the screenshot actually ends). With Snagit, this can be accomplished with literally 2 clicks:
- [x] You mention that subscribers can access the My Subscriptions page after subscribing—where else can they access it from? (The footer of any emails they receive.) I recommend mentioning that as well (a screenshot of that is not necessary).
- [x] "Comments/" needs a space after 'Comments'
- [x] "Choosing Post", "Choosing Comment"—these should be headers and not just bold text. I suggest H3.
- [x]  Updated Screenshots

Ready for check, thanks!

**Comment by raamdev** [comment]
Looks much better! Please see my notes on the screenshots here: https://github.com/websharks/comment-mail-kb/issues/31#issuecomment-309596113

**Comment by renzms** [comment]
@raamdev 

Updated screens, thanks!

**Comment by raamdev** [comment]
> by accessing their My Comment Subscription Page via the link found at the bottom

Bottom of where?



> There they can customize their subscriptions from

Reiterate where "There" is (e.g., "From the My Comment Subscriptions page, they can customize...")

> Choosing Post

Those headers above the screenshots are not necessary here, since the screenshots all contain the same headers and since there's no text in between the screenshots. The headers just look redundant. 

----

Also, from now on, please add `toc-enable: off` to the YAML markup at the top. That will disable the Table of Contents generation on the KB Article when it's published. If there aren't multiple headers or if the KB article is really short (e.g., just 1  or 2 headers), then it doesn't make sense to unnecessarily generate a TOC.

**Comment by renzms** [comment]
@raamdev 

Updated with corrections, please check. Thanks! :)
